language: php

php:
  - 5.6

before_script:
  - composer install --dev
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash
  - mysql -e 'create database olivier_test;'

script:
  - phpunit -c app
  - phpcs --standard=PSR2 ./src

notifications:
  email:
    - genvaldartem@gmail.com
